name: Continuous Integration

on: 
  pull_request:

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: '15.0.0'
          
      - name: Upgrade npm to v7
        run: npm install -g npm@7
      

      - name: Ensure ESLint and Prettier are installed
        run: |
          npm install --save-dev eslint
          npm install --save-dev prettier
          
      - name: Run lint
        run: npm run lint

      - name: Run Prettier
        run: npm run prettier

      - name: Run Tests
        run: npm run test

      - name: Build Project
        run: npm run build
