name: Continuous Integration

on: 
  pull_request:

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: '16.x'

      - name: Install dependencies, lint, format, test and build
        run: |
          npm install
          npm run lint
          npm run prettier
          npm run test
          npm run build

